enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'RESOURCE_NOT_FOUND_ERROR',
  NOT_AUTHENTICATED = 'NOT_AUTHENTICATED_ERROR',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED_ERROR',
  INPUT_INVALID = 'INPUT_INVALID_ERROR',
  REQUEST_FAILED = 'BAD_GATEWAY_ERROR',
  INTEGRATION_FAILED = 'BAD_GATEWAY_ERROR',
}

export { ErrorCode };
