FROM node:14.9.0-alpine
ENV NODE_ENV=development
RUN mkdir /app && chown -R node:node /app
WORKDIR /app
USER node
COPY --chown=node:node package.json yarn.lock ./
RUN yarn install
COPY --chown=node:node . .
ENTRYPOINT ["node_modules/.bin/tsc-watch", "--noClear", "--onSuccess", "node -r source-map-support/register ./dist/index.js"]
