export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  AUTHENTICATION_ERROR = 'UNAUTHENTICATED',
  AUTHORIZATION_ERROR = 'UNAUTHORIZED',
  INPUT_VALIDATION_ERROR = 'INPUT_INVALID_ERROR',
  INTEGRATION_ERROR = 'BAD_GATEWAY',
  REQUEST_FAILED = 'BAD_GATEWAY_ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  MAX_LOGIN_ATTEMPTS = 'MAX_LOGIN_ATTEMPTS',
  ORGANISATION_NOT_FOUND = 'ORGANISATION_NOT_FOUND',
}
